### ISSUE TITLE
Return a value for "Afternoon"

### ISSUE THREAD

**Issue by chelsea** [thebestday/sutime_parser#1]
"Friday afternoon" is currently discarded, an arbitrary afternoonish time should be returned instead.

**Comment by WhitneyTBD** [comment]
Morning = 9 am
Afternoon = 3 pm
Evening = 6 pm
Night = 8 pm

Extras (dreamin')
Breakfast = 9 am
Lunch = 12:30 pm
Dinner = 7:00 pm

**Comment by chelsea** [comment]
The extras aren't likely going to happen, sutime doesn't pick them up as times, plus you'll run into issues like:

"Want to get lunch at noon?" which should only return the time directly stated

**Comment by chelsea** [comment]
Fixed by 7b7b149

**Comment by WhitneyTBD** [comment]
Woo! Thanks so much.
