### ISSUE TITLE
When just a date is mentioned it will be the occurrence in the current week

### ISSUE THREAD

**Issue by chelsea** [thebestday/sutime_parser#3]
This causes some inconsistent behaviour.

ie. On Tuesday 6 Jan mentioning "Monday" will return Monday 5 Jan, when it is more expected to be Monday 12 Jan

Mentioning "Wednesday" on the same day as example above will return "Wednesday 7 Jan"

**Comment by chelsea** [comment]
Fixed by 0e3ecc31aac515c01867328b6f62bd6fce11c98c

**Comment by WhitneyTBD** [comment]
I'm unsure if this belongs to this issue but I am seeing similar inconsistent behaviour for some mentions of days with dates, without specifying the month. e.g. "Saturday the 24th".

Most attempts are parsing correctly, as in: "Thursday the 22nd" is correctly returned as 'Thursday 22nd January'.

However, "Saturday the 31st" is intended as 'Saturday 31st January' but is returning as 'Wednesday 31st December'. 

I have not been able to figure out why this exception is occurring so far.
